#!/usr/bin/env python3

import re
from pathlib import Path

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
QIDFILE = ROOT / 'tools' / 'midnight_quest_ids.txt'
WOWHEAD_URL = 'https://www.wowhead.com/quests/midnight'


def discover_ids():
    ids = set()

    print(f'[+] Opening {WOWHEAD_URL}')

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125 Safari/537.36',
            viewport={'width': 1600, 'height': 1200},
        )

        # Do not use networkidle on Wowhead. It keeps analytics/ad/background
        # requests alive long enough to timeout in GitHub Actions.
        page.goto(WOWHEAD_URL, wait_until='domcontentloaded', timeout=60000)

        # Try to let the Listview render, but do not fail if the selector never
        # appears. The page may still expose IDs in inline JS/HTML.
        try:
            page.wait_for_selector('a[href*="quest="]', timeout=20000)
        except PlaywrightTimeoutError:
            print('[!] Quest links did not render before timeout; falling back to page HTML/text')

        page.wait_for_timeout(3000)

        html = page.content()

        try:
            text = page.locator('body').inner_text(timeout=10000)
        except PlaywrightTimeoutError:
            text = ''

        try:
            hrefs = page.eval_on_selector_all('a[href]', 'els => els.map(a => a.getAttribute("href"))')
        except Exception:
            hrefs = []

        browser.close()

    for source in [html, text, '\n'.join(hrefs or [])]:
        if not source:
            continue

        for match in re.findall(r'(?:quest=|/quest/)(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

        for match in re.findall(r'"id"\s*:\s*(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

        for match in re.findall(r'"questId"\s*:\s*(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

    print(f'[+] Discovered {len(ids)} candidate quest IDs')
    return sorted(ids)


def write_seed_file(ids):
    output = []
    output.append('# Midnight quest IDs discovered from Wowhead JS-rendered quest index.')
    output.append('# Generated by tools/discover_midnight_quest_ids.py')
    output.append('# One quest ID per line. Blank lines and # comments are ignored.')
    output.append('')

    for qid in ids:
        output.append(str(qid))

    QIDFILE.write_text('\n'.join(output) + '\n', encoding='utf-8')
    print(f'[+] Wrote {len(ids)} quest IDs to {QIDFILE}')


def main():
    ids = discover_ids()

    if not ids:
        raise SystemExit('[!] No Midnight quest IDs were discovered. Wowhead layout may have changed or blocked rendering.')

    write_seed_file(ids)


if __name__ == '__main__':
    main()
