#!/usr/bin/env python3

import re
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
QIDFILE = ROOT / 'tools' / 'midnight_quest_ids.txt'
WOWHEAD_URL = 'https://www.wowhead.com/quests/midnight'


def discover_ids():
    ids = set()

    print(f'[+] Opening {WOWHEAD_URL}')

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125 Safari/537.36'
        )
        page.goto(WOWHEAD_URL, wait_until='networkidle', timeout=120000)

        # Give Wowhead's client-side listview a little extra time if needed.
        page.wait_for_timeout(5000)

        html = page.content()
        text = page.locator('body').inner_text(timeout=30000)
        hrefs = page.eval_on_selector_all('a[href]', 'els => els.map(a => a.getAttribute("href"))')

        browser.close()

    for source in [html, text, '\n'.join(hrefs or [])]:
        for match in re.findall(r'(?:quest=|/quest/|/quest=)(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

        for match in re.findall(r'"id"\s*:\s*(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

        for match in re.findall(r'"questId"\s*:\s*(\d+)', source):
            qid = int(match)
            if qid >= 90000:
                ids.add(qid)

    return sorted(ids)


def write_seed_file(ids):
    output = []
    output.append('# Midnight quest IDs discovered from Wowhead JS-rendered quest index.')
    output.append('# Generated by tools/discover_midnight_quest_ids.py')
    output.append('# One quest ID per line. Blank lines and # comments are ignored.')
    output.append('')

    for qid in ids:
        output.append(str(qid))

    QIDFILE.write_text('\n'.join(output) + '\n', encoding='utf-8')
    print(f'[+] Wrote {len(ids)} quest IDs to {QIDFILE}')


def main():
    ids = discover_ids()

    if not ids:
        raise SystemExit('[!] No Midnight quest IDs were discovered. Wowhead layout may have changed or blocked rendering.')

    write_seed_file(ids)


if __name__ == '__main__':
    main()
